title: Nishant Vemulakonda # your name (or website title)
logo: "/images/ProfilePicture.png?raw=true" # your photo (or logo)
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <b>Professional Summary</b>
  <br><br>
  ‣Prolific, experienced Blockchain Developer with 7+ years of rich IT experience.
  <br><br>
  ‣Strong Programming skills in Solidity, Python, JavaScript
  <br><br>
  ‣Passionate about building world class DApps on Ethereum smart contracts
  <br><br>
  ‣Excellent understanding of Ethereum smart contract development lifecycle.
  <br><br>
  <a href="https://www.linkedin.com/in/nishant-vemulakonda/">LinkedIn</a> 
  <br><br>
  <a href="https://nishantv.medium.com">Medium</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-202901452-1 # your Google Analytics tracking ID here
